- components/page/footer/PageFooterUpper.vue
- components/page/footer/__tests__/__snapshots__/PageFooter.test.js.snap
> Fix University search - Duplicate labels

- components/tabs/Tab.vue
- components/tabs/Tabs.vue
[#1128](https://github.com/unimelb/find-a-course/issues/1128)
> Fix (Tabs): 1128 Accessibility Missing form label

- components/page/megamenu/MegaMenu.vue
- components/page/search/PageSearchForm.vue
[#1162](https://github.com/unimelb/find-a-course/issues/1162)
> fix(accessibility): 1162 duplicate aria label

- package.json
- yarn.lock
package.json: Update webpack-dev-server package to webpack-dev-server@3.1.14 to fix vulnerability
> package.json: Update webpack-dev-server

- components/page/footer/index.css
> feature(css): liveagent css

- components/focusWrapper/FocusWrapper.vue
- components/focusWrapper/stories/Story1.vue
- components/focusWrapper/stories/Story2.vue
- components/focusWrapper/stories/index.js
> (feature/component) Add generic focus wrapper component with stories

- targets/lib/index.js
> (chore) register "focus wrapper" component in target lib

- targets/lib/index.js
Closes [#69](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/69)
> feat(target): add svgIcon to cms matrix target

- components/page/navigation/InPageNavigation.vue
- components/page/navigation/__tests__/InPageNavigation.test.js
- components/page/navigation/stories/InPageNavigationDefault.vue
- targets/vue/index.js
- Added simple tests to the component.
- Added FocusWrapper to the target ( Vue ).
Issue: [21](https://github.com/unimelb/ffam-prototype/issues/21)
> feat(component): In Page Navigation

- README.md
> chore(documentation): Update documentation for CMS testing

- README.md
> chore(documentation): update new component targets doc

- components/section/stories/SplitSection/Story1.vue
closes pattern library task for -> https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/94
> chore(component): Update story for split section component

- components/page/navigation/InPageNavigation.vue
- components/page/navigation/OutPageNavigation.vue
- components/page/navigation/stories/InPageNavigationDefault.vue
- components/page/navigation/stories/NavigationCollapsedDefault.vue
- components/page/navigation/stories/OutPageNavigationDefault.vue
ZenHub ticket: [#115](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/115)
> feat(component): in page nav added focus wrapper

- README.md
ZenHub ticket: [#91](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/91)
> chore(docs): dos and dont regarding to self-closing component

- components/tabs/Tab.vue
> fix(accessibility): tabs aria-label

- components/page/navigation/InPageNavigation.vue
- components/page/navigation/OutPageNavigation.vue
- components/page/navigation/stories/InPageNavigationDefault.vue
- components/page/navigation/stories/OutPageNavigationDefault.vue
- components/page/navigation/stories/in-page-navigation-docs.md
- components/page/navigation/stories/out-page-navigation-docs.md
Ticket: [#170](https://github.com/unimelb/ffam-prototype/issues/170)
- Fixed the documentation explanning how to implement the component: 
`in-page-navigation` and `out-page-navigation`
> fix(component): in page navigation implementation docs

- pre-push.sh
A modification of the pre-push script
We want NO local commits when pushing to dev (or $protected_branch)
and ask to confirm.
We will make an exception to the 'don't push to dev branch' rule if:
1. you are on a clean local dev branch
2. you are pushing to the remote dev branch
3. you want **only** to trigger a new npm build with a new version number.
This hook will check that remote and local are the same. That is, same version number and no local commits pending.
Then it will increment the version number, commit and push with an 'updated version number' message
This will trigger the dev build as usual, but the incremented version number will create a new npm version of pattern-lib too.
> Add checkCommits guard function

- .eslintrc
- .stylelintrc
- components/page/megamenu/MegaMenu.vue
- components/page/megamenu/MegaMenuTitle.vue
- components/page/megamenu/__tests__/MegaMenuTitle.test.js
- components/page/megamenu/__tests__/__snapshots__/MegaMenuTitle.test.js.snap
- components/page/megamenu/_mega-menu-title.css
- components/page/megamenu/_mega-menu.css
- components/page/megamenu/stories/MegaMenuTitleAperture.vue
- components/page/megamenu/stories/MegaMenuTitleProp.vue
- components/page/megamenu/stories/index.js
- added aperture option
- added aperture color prop
- unit tests
- styling
> Comp - 221: Mega menu title update

- components/cards/stories/GenericCard/Story1.vue
- components/cards/stories/GenericCard/Story2.vue
- components/cards/stories/GenericCard/Story3.vue
- components/cards/stories/GenericCard/Story4.vue
- components/cards/stories/GenericCard/Story5.vue
- components/cards/stories/GenericCard/Story6.vue
- components/cards/stories/GenericCard/generic-card-docs.md
- components/focus-wrapper/stories/Story1.vue
- components/focus-wrapper/stories/Story2.vue
- components/focus-wrapper/stories/Story3.vue
- components/focus-wrapper/stories/Story4.vue
- components/focus-wrapper/stories/Story5.vue
- components/focus-wrapper/stories/Story6.vue
- components/page/megamenu/stories/MegaMenuTitleAperture.vue
- components/page/megamenu/stories/mega-menu-docs.md
Ticket: [#244](https://github.com/unimelb/ffam-prototype/issues/244)
> chore(documentation): update stories and documentation

- components/_utils.css
- components/section/stories/Section/Story6.vue
- components/section/stories/Section/index.js
Ticket: [#4](https://github.com/unimelb/ffam-prototype/issues/4)
> feature(css): section background color black

- components/section/stories/Section/Story1.vue
- components/section/stories/Section/Story2.vue
- components/section/stories/Section/Story3.vue
- components/section/stories/Section/Story4.vue
- components/section/stories/Section/Story5.vue
- components/section/stories/Section/Story6.vue
Ticket: [#4](https://github.com/unimelb/ffam-prototype/issues/4) 
@TimMansell A tried to cover all the cases where the Section background will be black, but the content inside does not turn into white, hopefully, is fully covered.
> feature(css): added bg black for sections

- components/page/footer/PageFooterSitemap.vue
> chore(footer): update links

- components/cards/CardFeaturesPanel.vue
- components/cards/__tests__/CardFeaturesPanel.test.js
- components/cards/__tests__/__snapshots__/CardFeaturesPanel.test.js.snap
- components/cards/_card-features-panel.css
- components/cards/index.css
- components/cards/stories/FeaturesPanel/Story1.vue
- components/cards/stories/FeaturesPanel/Story2.vue
- components/cards/stories/FeaturesPanel/Story3.vue
- components/cards/stories/FeaturesPanel/features-panel.md
- components/cards/stories/FeaturesPanel/index.js
- components/cards/stories/index.js
- targets/lib/index.js
- targets/vue/index.js
Ticket: [#200](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/200)
> feature(component): feature panel

- components/cards/_generic-card.css
- components/cards/stories/GenericCard/Story3.vue
- components/cards/stories/GenericCard/Story4.vue
- components/cards/stories/GenericCard/Story5.vue
Ticket: [#292](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/292)
> fix(css): sub title css

- components/page/megamenu/_mega-menu-title.css
https://github.com/unimelb/pattern-lib/issues/1009
> Update faculty name visited colour to white

- components/page/megamenu/MegaMenu.vue
- components/page/megamenu/MegaMenuTopNavigation.vue
- components/page/megamenu/__tests__/__snapshots__/MegaMenuTopNavigation.test.js.snap
> bug fix - Accessibility Mega Menu

- components/cards/CardStat.vue
- components/cards/__tests__/CardStat.test.js
- components/cards/_card.css
- components/cards/stories/FocusBox/Story7.vue
- components/cards/stories/FocusBox/index.js
Ticket: [#307](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/307)
Breaking change in `ffam-prototype`
> fix(css): card.css fix black option

- components/cards/CardFeaturesPanel.vue
- components/cards/CardShowcaseProfile.vue
- components/cards/__tests__/CardShowcaseProfile.js
- components/cards/__tests__/__snapshots__/CardShowcaseProfile.js.snap
- components/cards/_card-showcase-profile.css
- components/cards/stories/FeaturesPanel/Story1.vue
- components/cards/stories/FeaturesPanel/Story3.vue
- components/cards/stories/Profiles/Story1.vue
- utils/placeholders.js
Ticket: [#293](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/293)
>  fix(component): card showcase profile

- components/index.css
- components/page/navigation/InPageNavigation.vue
- components/page/navigation/OutPageNavigation.vue
- components/page/navigation/index.css
PR to fix css using BEM and make it possible to override in FFAM
> fix(component): in page nav css

- components/cards/CardFeaturesPanel.vue
- components/cards/CardImage.vue
- components/cards/CardImageList.vue
- components/cards/CardLink.vue
- components/cards/CardNews.vue
- components/cards/CardShowcaseProfile.vue
- components/cards/CardStaffList.vue
- components/cards/GenericCard.vue
- components/cards/__tests__/CardFeaturesPanel.test.js
- components/cards/__tests__/__snapshots__/CardEvents.test.js.snap
- components/cards/__tests__/__snapshots__/CardFeaturesPanel.test.js.snap
- components/cards/__tests__/__snapshots__/CardLink.test.js.snap
- components/cards/__tests__/__snapshots__/CardShowcaseProfile.js.snap
- components/cards/__tests__/__snapshots__/CardStaffList.test.js.snap
- components/cards/__tests__/__snapshots__/GenericCard.test.js.snap
- components/cards/_card-stafflist.css
- fix(component): card features  panel accessibility heading level
- fix(component): card image aria label   accessibility
- fix(component): card image list aria label accessibility
- fix(component): card link arial label  accessibility
- fix(component): generic card to accept aria   label
- fix(component): card staff list   to accept aria-label and hover underline
- fix(component): accept aria-label for the  images
- fix(component): card news clickable area and aria-label accessibility
> fix(accessibility): accessibility fixes

- components/cards/_card-generic.css
- components/cards/stories/GenericCard/Story7.vue
- components/cards/stories/GenericCard/index.js
Ticket: [#370](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/370)
> fix(component): generic card links color accessibility

- components/cards/stories/FocusBox/Story3.vue
- components/icons/SvgIcon.vue
- components/page/breadcrumbs/__tests__/__snapshots__/PageBreadcrumbs.test.js.snap
Ticket: [#355](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/355)
> fix(icons): aria label

- components/page/navigation/index.css
>  In Page Nav - z-index

- components/cards/_card-showcase-profile.css
- components/cards/stories/Profiles/Story1.vue
Ticket: [#319](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/319)
> fix(component): showcase perfomer card bg color white

- components/cards/CardFeaturesPanel.vue
- components/cards/__tests__/__snapshots__/CardFeaturesPanel.test.js.snap
Ticket: [#332](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/332)
> fix(component): features panel bg color

- components/cards/_card-events.css
- components/cards/_card-generic.css
Ticket: [#312](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/312)
> fix(component): cards divider line

- components/forms/_select.css
- components/section/_section.css
Ticket: https://jira.unimelb.edu.au/browse/TS-307
> fix(component): select black color

- components/cards/_card.css
- components/cards/stories/Events/Story1.vue
[#493](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/493)
> fix(cards): change card__thumb height to min-height.  

- components/index.css
- components/info-panel/InfoPanel.vue
- components/info-panel/__tests__/InfoPanel.js
- components/info-panel/__tests__/__snapshots__/InfoPanel.js.snap
- components/info-panel/index.css
- components/info-panel/stories/Story1.vue
- components/info-panel/stories/index.js
- components/info-panel/stories/info-panel.md
- targets/lib/index.js
- targets/vue/index.js
- yarn.lock
Ticket: [#425](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/425)
> feature(component): info panel

- package.json
- yarn.lock
Enable windows based machines to run npm/yarn commands using `cross-env` package
> Install cross-env so repo can be run on a windows based machine

- components/page/header/index.css
- components/page/megamenu/MegaMenu.vue
- components/page/megamenu/_mega-menu.css
Ticket: [#501](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/501)
> fix(component): mega menu logo on mobile

- components/icons/SvgIcon.vue
- components/page/breadcrumbs/__tests__/__snapshots__/PageBreadcrumbs.test.js.snap
Ticket: [#464](https://github.com/unimelb/ffam-prototype/issues/464)
> fix(component): icons capitalisation

- components/forms/_select.css
Ticket: [#369](https://github.com/unimelb/ffam-prototype/issues/369)
> fix(component): select color contrast

- components/page/navigation/index.css
- components/page/navigation/stories/InPageNavigationDefault.vue
Ticket: [#504](https://github.com/unimelb/ffam-prototype/issues/504)
> fix(component): in page nav link order

- components/buttons/stories/StoryButtonElement.vue
> fix(story): button text

- components/cards/CardFocusBox.vue
- components/focus-wrapper/stories/Story6.vue
- components/section/stories/Focus/Story4.vue
> fix(console): issues

- package-lock.json
- package.json
- yarn.lock
> fix(command): yarn start:lib

- components/header/index.css
> fix(component): header l3

- components/megamenu/_mega-menu-title.css
Ticket: [#526](https://github.com/unimelb/ffam-prototype/issues/526)
> fix(component): mega menu title

- components/social-media-bar/SocialMediaBar.vue
- components/social-media-bar/__tests__/__snapshots__/SocialMediaBar.test.js.snap
- components/social-media-bar/index.css
Some recommendations for the social media bar component:
Making classnames more generic
Using modifiers instead of new element
> chore(component): channel bar titles html & css recommendations

- components/megamenu/_mega-menu.css
Ticket: [#543](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/543)
> fix(component): mega menu inner colour

- components/breadcrumbs/index.css
- components/carousel/Carousel.vue
- components/carousel/__tests__/Carousel.test.js
- components/carousel/index.css
- components/carousel/sample.json
- components/carousel/stories/carousel-doc.md
Tickets: #1217 [#542](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/542)
> update(component): carousel image position and story

- components/cards/GenericCard.vue
- components/cards/__tests__/GenericCard.test.js
- components/cards/__tests__/__snapshots__/GenericCard.test.js.snap
- components/cards/_card-generic.css
- components/cards/_card.css
- components/cards/stories/GenericCard/Story6.vue
Ticket: [#544](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/544)
> fix(component): generic card images height

- components/typography/_titles.css
Ticket: [#546](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/546)
> chore(headings): letter spacing lager heading classes

- components/article-wrap/ArticleWrap.vue
- components/footer/PageFooterUpper.vue
- components/social-list/SocialListGeneric.vue
- components/social-list/__tests__/SocialList.test.js
- components/social-list/__tests__/__snapshots__/SocialList.test.js.snap
- components/social-list/stories/SocialListGeneric.vue
- components/social-list/stories/index.js
- components/social-media-bar/SocialMediaBar.vue
- components/social-media-bar/__tests__/__snapshots__/SocialMediaBar.test.js.snap
- components/social-media-bar/index.css
Make the social list bar reusable so we can use in other components as well such as Event Header https://zeroheight.com/17lwnkf17/p/1716a8/i/3066168
> refactor(component): social list bar to be reusable

- components/accordion/index.css
- components/typography/_headings.css
[#551](https://github.com/unimelb/ffam-prototype/issues/)
> chore(headings) add letter-spacing to missing classes

- components/social-media-bar/SocialMediaBar.vue
Ticket: [#548](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/548)
> fix(component): social media bar icons

- components/carousel/index.css
- components/figure/_full-width-image.css
Ticket: [#552](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/552)
> chore(component): Carousel and Full width image consistent image height

- components/cards/CardNewsTag.vue
- components/cards/_card-events.css
- components/cards/_card-generic.css
- components/cards/_card-news-tag.css
- components/cards/index.css
Ticket: [#547](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/547)
[#544](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/544)
> fix(component): cards subtitle and excerpt

- components/megamenu/_mega-menu.css
- components/search/_header-tools.css
> fix(constrast): search and hamburger menu

- webpack.config.base.js
> fix(minification) force cssnano to not compress keyframe names

- targets/lib/index.js
- targets/vue/index.js
I forgot to export that component before.
> chore(export): social list generic

- components/megamenu/MegaMenu.vue
- components/megamenu/_mega-menu-title.css
- components/megamenu/_mega-menu.css
Ticket: [#468](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/468)
> fix(component): mega menu title identifier line IE11

- components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
- components/filter/accordion/AccordionFilter.vue
Ticket: [#568](https://github.com/unimelb/ffam-prototype/issues/568)
> feat(filter): accordion redesign

- components/media-gallery/_media-gallery.css
Ticket: https://github.com/unimelb/pattern-lib/issues/1273
> fix(component): media gallery thumbs aligment

- components/header/page-header-event.css
Ticket: [#561](https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/561)
> chore(component): event header update styling

- components/nav-bar/index.css
> fix(component): tab indicator floating

- components/footer/index.css
- components/index.css
- third-party/salesforce.css
Ticket: https://jira.unimelb.edu.au/browse/TS-481
> chore(liveagent): add live chat css for MSPACE / Salesforce

- components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
- components/filter/cards/CardsFilter.vue
- components/tags/Tags.vue
- components/tags/index.css
> chore(filter): cards update to accept tags

- components/_base.css
- components/cards/_card-generic.css
- components/cards/stories/Events/Story3.vue
- components/cards/stories/Events/index.js
> fix(component): cards color bg inverted

- components/header/split-section-header.css
Ticket: https://github.com/unimelb/pattern-lib/issues/1317
> fix(component): split section header

- components/media-gallery/_media-gallery.css
> fix(media gallery) fix z-index so it overlays footer

- components/footer/PageFooterSitemap.vue
- components/footer/PageFooterUpper.vue
> chore(component): page footer add accomodation link and fix phone number

- components/cards/_card-features-panel.css
Ticket: https://github.com/unimelb/pattern-lib/issues/1318
> fix(component): card features panel title

- components/footer/PageFooterSitemap.vue
> chore(component): footer update strategy link

- components/modal/ModalDialog.vue
- components/modal/__tests__/ModalDialog.test.js
- components/toggle/ToggleBlock.vue
- utils/focusable-elements.js
> fix(ToggleBlock|Modal) fix focusable elements error

- components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
- components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
- components/filter/filters-core/filters/DropdownFilter.vue
- components/forms/StyledSelect.vue
- components/forms/__tests__/__snapshots__/StyledSelect.test.js.snap
- components/forms/_select.css
- components/tabs/Tabs.vue
- components/tabs/index.css
- components/tabs/stories/TabsSelect.vue
- components/tabs/stories/index.js
https://github.com/unimelb/find-a-course/issues/1491
This PR only covers the dropdown part (minus the 3 courses available)
Updated tabs to allow for a select dropdown tab changer.
Components affected:
- styled select https://deploy-preview-1351--pattern-lib-unimelb.netlify.com/?selectedKind=Forms&selectedStory=Styled%20select&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
- filters https://deploy-preview-1351--pattern-lib-unimelb.netlify.com/?selectedKind=Filter%20%2F%20Components&selectedStory=Accordion%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
- tabs https://deploy-preview-1351--pattern-lib-unimelb.netlify.com/?selectedKind=Tabs&selectedStory=Tabs%2C%20using%20a%20select&full=0&addons=1&stories=1&panelR …
> feature(styled-select) update to new design

- components/footer/PageFooterSitemap.vue
> chore(update) update footer with new about us link

- components/filter/__tests__/__snapshots__/AccordionFilter.test.js.snap
- components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
- components/forms/StyledSelect.vue
- components/forms/__tests__/__snapshots__/StyledSelect.test.js.snap
- components/forms/_select.css
- components/forms/stories/StyledSelect.vue
- package.json
- postcss.config.js
- targets/lib/index.js
- targets/vue/index.js
- yarn.lock
Make it compatible with CMS
Add new `<StyledSelect>` & `<styled-select>` to targets
> chore(update) Update styled-select to not use svgicon

- components/buttons/index.css
> fix(component) fix button hover states

- components/forms/_select.css
- components/tabs/Tabs.vue
- components/tabs/index.css
- components/tabs/stories/TabsSelect.vue
- components/tabs/stories/tabsSelect.md
https://deploy-preview-1368--pattern-lib-unimelb.netlify.com?selectedKind=Tabs&selectedStory=Tabs%2C%20using%20a%20select&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
> update(component) implement label for tabs select

- components/tabs/Tabs.vue
- components/tabs/__tests__/Tabs.test.js
- components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
- components/tabs/index.css
- components/tabs/stories/TabsAlt.vue
- components/tabs/stories/tabsAlt.md
- This PR doesn't cover scrolling of tabs.
- Tided up some media queries
https://zeroheight.com/17lwnkf17/p/410157/i/5484117
> feature(component) Update tabs alternative

- .github/PULL_REQUEST_TEMPLATE.md
- components/forms/_select.css
- components/tabs/Tabs.vue
- components/tabs/__tests__/Tabs.test.js
- components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
- components/tabs/index.css
- components/tabs/stories/TabsAlt.vue
- components/tabs/stories/TabsSelect.vue
- components/tabs/stories/tabsAlt.md
- components/tabs/stories/tabsSelect.md
- package.json
> Deploy 5.4.0

- components/forms/_select.css
- components/tabs/index.css
- components/tabs/stories/TabsSelect.vue
> fix(component): selector blue label

- components/tabs/index.css
> fix(component) Tabs - Fix white space above select

- components/forms/_select.css
> fix(component): selector dropdown

- components/forms/_select.css
- components/tabs/Tabs.vue
- components/tabs/index.css
- package.json
> Deploy v5.5.1

- components/tabs/index.css
> fix(component): tabs active

- .stylelintrc
- components/footer/PageFooterUpper.vue
> component(footer) update visa link

- components/_utils.css
- components/buttons/ButtonIcon.vue
- components/buttons/index.css
Button text on left icon variant should be aligned to left
Set the vertical spacing between full with buttons to 1rem
> chore(component) Button adjustments

- components/listing/_logo-listing.css
> chore(component) Logo Listing grayscale

- components/buttons/index.css
- components/buttons/stories/StoryButtonCMSIcons.vue
> chore(component) migrate matrix button css to pattern lib

- .eslintrc
- .storybook/utils/create-story.js
- .storybook/utils/story-decorator.js
- components/accordion/Accordion.vue
- components/icons/SvgIcon.vue
- components/index.js
- components/megamenu/MegaMenu.vue
- components/modal/ModalDialog.vue
- components/nav/PageNav.vue
- components/search/PageSearch.vue
- components/shared/utils/vnode-to-element.js
- components/tabs/Tabs.vue
- components/toggle/ToggleBlock.vue
- components/toggle/ToggleBlockMobile.vue
- components/toggle/ToggleGroup.vue
- Improves readability of if statements.
- Updates to eslint to enforce if statements to use { & } and break them onto seperate line.
> chore(linting) code style readability

- .eslintrc
- components/nav/PageNav.vue
- components/navigation/InPageNavigation.vue
- package.json
- yarn.lock
Installed `eslint-plugin-unicorn`
Helps improve codebase by enforcing usage of modern functions and apis
> chore(linting) eslint-plugin-unicorn and rules

- .github/PULL_REQUEST_TEMPLATE.md
Added a checklist for a reviewer to check against before approving and merging a PR.
> chore(reviews) Add reviewer checklist tasks 

- components/cards/CardFocusBox.vue
- components/cards/_card-focus-box.css
- components/section/_section.css
- components/section/stories/Focus/Story1.vue
- components/section/stories/Focus/Story2.vue
- components/section/stories/Focus/Story3.vue
- components/section/stories/Focus/Story4.vue
- components/section/stories/Focus/Story5.vue
> fix(component): section focus box btn

- components/footer/PageFooterSitemap.vue
- components/footer/PageFooterUpper.vue
Fixes Same link text points to different URLs, accessibility issue caused by trailing slashes in footer links.
Fixes # 1446
> removed trailing slashes

- components/footer/PageFooterSitemap.vue
> chore(footer): update shop link

- components/cards/CardPathfinder.vue
- components/cards/__tests__/__snapshots__/CardPathfinder.test.js.snap
- components/cards/_card-pathfinder.css
The problem in iOS overlapping buttons
Fix:
> fix(component): card pathfinder to use focus wrapper

- components/filters/components/filter-widget/FilterWidget.vue
- utils/trackAnalytics.js
> feat(filter): analytics

- components/base/base-checkbox/BaseCheckbox.vue
- components/carousel/Carousel.vue
- components/filters/components/filter-box/FilterBox.vue
- components/filters/components/filter-dropdown/FilterDropdown.vue
- components/filters/components/filter-dropdown/__tests__/__snapshots__/FilterDropdown.test.js.snap
- components/filters/components/filter-dropdown/stories/filter-dropdown.md
- components/media-gallery/MediaGallery.vue
- components/media-gallery/ThumbnailGallery.vue
- components/megamenu/MegaMenu.vue
- components/modal/ModalDialog.vue
- components/search/PageSearch.vue
- components/tabs/Tabs.vue
> fix(filters) accessibility

- components/buttons/ButtonCard.vue
- components/buttons/index.css
- components/buttons/stories/StoryButtonCard.vue
- components/buttons/stories/index.js
- components/profiles/stories/Accordion.vue
- targets/lib/index.js
- targets/vue/index.js
Fixes https://jira.unimelb.edu.au/browse/VOD-111
preview: https://deploy-preview-1466--pattern-lib-unimelb.netlify.app/?selectedKind=Buttons%2FTypes&selectedStory=Button%20Card&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
> feat(component): button card

- components/index.css
- components/print.css
Adding print style for footer, header and specific pages for About site & Study site
SQUIZ JIRA Ticket #UOMDEV-8
> Print style for About site & Study site

- components/_grid.css
- components/cards/CardFeaturesPanel.vue
- components/cards/CardRoundedFigure.vue
- components/cards/__tests__/__snapshots__/CardFeaturesPanel.test.js.snap
- components/cards/_card-rounded-figure.css
- components/cards/index.css
- components/cards/stories/FeaturesPanel/Story1.vue
- components/cards/stories/FeaturesPanel/Story2.vue
- components/cards/stories/FeaturesPanel/Story3.vue
- components/cards/stories/RoundedFigure/Story1.vue
- components/cards/stories/RoundedFigure/index.js
- components/cards/stories/index.js
- components/figure/FigureRounded.vue
- components/figure/_figure-wrap.css
- components/figure/stories/Story20.vue
- targets/lib/index.js
- targets/vue/index.js
Fixes # https://jira.unimelb.edu.au/browse/VOD-120
[PREVIEW](https://deploy-preview-1472--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FRounded%20Figure&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): card rounded figure

- components/cards/CardFeaturesPanel.vue
- components/cards/__tests__/CardFeaturesPanel.test.js
- components/cards/_card-features-panel.css
- components/cards/stories/FeaturesPanel/Story4.vue
- components/cards/stories/FeaturesPanel/index.js
https://jira.unimelb.edu.au/browse/VOD-149
[PREVIEW](https://5f2ca6c63412670008995d30--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FFeatures%20Panel&selectedStory=Features%20Panel%20%284%20Col%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): redesign features panel

- components/filters/components/filter-dropdown/FilterDropdown.vue
- components/filters/components/filter-dropdown/__tests__/__snapshots__/FilterDropdown.test.js.snap
- components/screen-reader-jump-to/ScreenReaderJumpTo.vue
> fix(warn): vue tip and warn

- components/buttons/index.css
- components/index.css
- components/section/_two-column-round-image.css
- components/todo-list/README.md
- components/todo-list/TodoList.vue
- components/todo-list/__tests__/TodoList.test.js
- components/todo-list/__tests__/__snapshots__/TodoList.test.js.snap
- components/todo-list/index.css
- components/todo-list/stories/Default.vue
- components/todo-list/stories/index.js
- targets/lib/index.js
- targets/vue/index.js
Fixes # https://jira.unimelb.edu.au/browse/VOD-132
[PREVIEW](https://deploy-preview-1471--pattern-lib-unimelb.netlify.app/?selectedKind=Todo%20List&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): todo list

- components/cards/CardImageListing.vue
- components/cards/_card-image-listing.css
- components/cards/index.css
- components/cards/stories/ImageListing/Story1.vue
- components/cards/stories/ImageListing/Story2.vue
- components/cards/stories/ImageListing/index.js
- components/cards/stories/index.js
- targets/lib/index.js
- targets/vue/index.js
Fixes # https://jira.unimelb.edu.au/browse/VOD-145
[PREVIEW](https://deploy-preview-1479--pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FImage%20Listing&selectedStory=Standlone&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): card image page listing

- components/campaign/_campaign-banner.css
Amended paragraph text width to match heading width; made line height on mobile same as desktop.
> Amend paragraph text width

- components/_grid.css
- components/_utils.css
- components/cards/CardRoundedFigure.vue
- components/cards/_card-rounded-figure.css
- components/listing/ListItem.vue
- components/sublink-menu/SublinkMenu.vue
- components/sublink-menu/SublinkMenuItem.vue
- components/sublink-menu/__tests__/__snapshots__/SublinkMenuItem.test.js.snap
- components/sublink-menu/index.css
- components/sublink-menu/stories/2ColText.vue
- components/sublink-menu/stories/2Columns.vue
- components/sublink-menu/stories/SublinkMenuDefault.vue
- components/sublink-menu/stories/SublinkMenuWithImageCard.vue
- components/sublink-menu/stories/WithImages.vue
- components/sublink-menu/stories/index.js
Fixes # https://jira.unimelb.edu.au/browse/VOD-141
[PREVIEW](https://deploy-preview-1480--pattern-lib-unimelb.netlify.app/?selectedKind=Sublink%20Menu&selectedStory=3%20Columns&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> redesign(component): sublink menu

- components/_utils.css
- components/_vars.css
- components/helpers/stories/Colours.vue
- components/section/stories/SectionThree/Story1.vue
- components/section/stories/SectionThree/index.js
- components/section/stories/index.js
[PREVIEW COLOURS](https://deploy-preview-1484--pattern-lib-unimelb.netlify.app/?selectedKind=Helpers&selectedStory=Colours&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[PREVIEW SECTION](https://deploy-preview-1484--pattern-lib-unimelb.netlify.app/?selectedKind=Section%2FThree%20Column&selectedStory=Header%20text%20with%20cta%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): 3 column section and colour helpers

- .storybook/config.js
- components/_utils.css
- components/block-quotation/index.css
- components/breadcrumbs/index.css
- components/campaign/index.css
- components/cards/_card-generic.css
- components/cards/_card-imagelist.css
- components/cards/_card-news.css
- components/cards/_card.css
- components/cards/stories/RoundedFigure/Story1.vue
- components/download-block/index.css
- components/filter/filters-core/results-count/index.css
- components/filters/components/filtered-results/index.css
- components/forms/_select.css
- components/header/page-header-event.css
- components/section/stories/SectionThree/Story1.vue
- components/sidebar/index.css
- components/sublink-menu/index.css
- components/sublink-menu/stories/SublinkMenuWithImageCard.vue
Component colour checks for new black global colour.
> chore(component): colour check

- .storybook/config.js
- components/_base.css
- components/_utils.css
- components/block-quotation/index.css
- components/breadcrumbs/index.css
- components/campaign/index.css
- components/cards/_card-contact.css
- components/cards/_card-generic.css
- components/cards/_card-imagelist.css
- components/cards/_card-link.css
- components/cards/_card-news.css
- components/cards/_card.css
- components/cards/stories/RoundedFigure/Story1.vue
- components/download-block/index.css
- components/filter/filters-core/results-count/index.css
- components/filters/components/filtered-results/index.css
- components/forms/_select.css
- components/header/page-header-event.css
- components/print.css
- components/section/stories/SectionThree/Story1.vue
- components/sidebar/index.css
- components/sublink-menu/index.css
- components/sublink-menu/stories/SublinkMenuWithImageCard.vue
> feat(colours): typography overhaul

- components/_base.css
- components/_vars.css
Adjusted standard and visited link colours for better contrast on non-white backgrounds; applied white paragraph text to the last dark background section.
> fix(styling): text contrast fixes

- components/megamenu/MegaMenu.vue
- components/megamenu/_mega-menu-top.css
- components/megamenu/_mega-menu.css
- components/megamenu/stories/HybridMenu.vue
- components/megamenu/stories/HybridMenuWithTopNav.vue
- constants/timers.js
Fixes https://github.com/unimelb/design-system-issues/issues/67
> chore(component): mega menu hover delay

- components/campaign/_campaign-banner.css
Various values changed to accommodate longer heading text and to correct alignment and image sizing at various breakpoints.
> fix(component): amend banner heights, font sizing, text alignment for Campaign Banner 2021

- components/cards/GenericCard.vue
- components/filter/cards-category/CardsFilterCategory.vue
- components/filter/index.css
- components/index.js
- components/side-panel/index.js
> chore(component): filter cards category

- components/cards/_card-generic.css
- components/filter/cards-category/CardsFilterCategory.vue
- components/filter/cards-category/cards.md
- components/filter/cards-category/data.json
- components/filter/index.css
- components/forms/_select.css
[PREVIEW](https://deploy-preview-1520--pattern-lib-unimelb.netlify.app/?selectedKind=Filter%2FComponents&selectedStory=Cards%20Filter%20Categories&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> fix(component): filters category css and animations

- components/filter/index.css
[preview](https://deploy-preview-1522--pattern-lib-unimelb.netlify.app/?selectedKind=Filter%2FComponents&selectedStory=Cards%20Filter%20Categories&full=1&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(filter): add video icon card filter

- components/filters/components/filter-box/FilterBox.vue
> fix(acessibility): filter box

- components/footer/PageFooterUpper.vue
> fix(accessibility): footer aria hidden

- components/filter/courses/CoursesFilter.vue
- components/filter/courses/courses.md
- components/filter/courses/data.json
- components/filter/index.css
- components/filter/stories/CoursesFilterStory.vue
- components/filter/stories/index.js
- targets/lib/index.js
- targets/vue/index.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> feat(filter): courses

- components/media-gallery/MediaGallery.vue
- components/modal/ModalDialog.vue
- components/modal/index.css
- components/modal/stories/ModalVideo.vue
- components/modal/stories/index.js
- helpers/pauseVideo.js
> feat(component): modal button with video

- components/footer/PageFooterSitemap.vue
- components/footer/PageFooterUpper.vue
- targets/lib/index.html
> chore(component): update footer

- components/buttons/index.css
Fixes https://github.com/unimelb/pattern-lib/issues/1438
> fix(component): button secondary border colour

- components/footer/index.css
Fixes https://github.com/unimelb/pattern-lib/issues/1552
> fix(component): footer accessibility requests

- components/modal/ModalDialog.vue
Fixes https://github.com/unimelb/pattern-lib/issues/1427
> fix(component): modal input trap

- components/megamenu/MegaMenu.vue
- helpers/isMobile.js
Fixes https://github.com/unimelb/pattern-lib/issues/1564
> fix(component): mega menu mobile viewport checker

- components/footer/PageFooterUpper.vue
- components/forms/stories/InlineSearchForm.vue
- components/forms/stories/InlineSearchFormInverse.vue
- components/forms/stories/InlineSearchFormMin.vue
- components/search/PageSearch.vue
- components/search/PageSearchForm.vue
- components/search/__tests__/__snapshots__/PageSearch.test.js.snap
- components/search/__tests__/__snapshots__/PageSearchForm.test.js.snap
Bug fix (accessibility aria-label button search)
> accessibility aria label btn search

- helpers/isMobile.js
- package.json
> fix(function): is mobile

- components/toggle/ToggleBlockMobile.vue
1. Clickable controls should have an ARIA role.
2. Clickable controls should be keyboard accessible.
> fix accessibility ToggleBlock

- components/cards/GenericCard.vue
- components/cards/__tests__/__snapshots__/CardEvents.test.js.snap
- components/cards/__tests__/__snapshots__/GenericCard.test.js.snap
- components/filter/__tests__/__snapshots__/CardsFilter.test.js.snap
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix accessibility GenericCard

- components/tabs/Tabs.vue
- components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
> fix accessibility tablist

- components/cards/_card-campaign.css
- components/cards/_card-generic.css
- components/profiles/accordion-profile/index.css
- components/section/_two-column-round-image.css
> chore(css): tidy grey text

- components/forms/stories/InlineSearchForm.vue
- components/typography/_headings.css
Fixes https://app.zenhub.com/workspaces/global-design-system-issues-tracker-603c265651b123001c916450/issues/unimelb/pattern-lib/1581
> fix(colour) heading classes

- components/cards/_card-generic.css
> fix(component): generic card font colour

- components/cards/CardCourse.vue
- components/cards/_card-course.css
- components/cards/stories/Course/Story3.vue
- components/cards/stories/Course/card-course.md
- components/cards/stories/Course/index.js
- utils/textHighlight.js
This includes style updates to the `CardCourse` component, as well as alternative styling as a search result, which highlights matching text within the name. This util function will be used on another future component.
> Style updates to card course component

- components/_utils.css
- components/helpers/stories/Backgrounds.vue
- components/helpers/stories/Colours.vue
- components/typography/stories/ListsInline.vue
- components/typography/stories/index.js
New utility classes which include:
- `.display-block` (display helper)
- `.col-grey-mid-2` (colour helper)
- `.bg-grey-light` (background helper)
- `.list-inline` (display a list inline)
- `.border-top` (add a faint border to the top)
> Add new utility classes

- components/footer/PageFooterUpper.vue
- components/footer/index.css
Fixes https://jira.unimelb.edu.au/browse/TS-1053
> remove(search): from page footer

- components/footer/PageFooter.vue
Fixes https://jira.unimelb.edu.au/browse/TS-1051
> remove(component): toggleblock from footer

- components/tabs/Tabs.vue
> fix(component): tabs console issue

- components/quick-links-menu/QuickLinksMenuItem.vue
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # SVG elements with graphic role attributes must have an accessible name.
> fix accessibility svg role

- components/cards/_card-course.css
- components/today/stories/Section/CourseIndex.vue
- components/today/stories/Section/index.js
Adding the mini course index to our list of sections.
[Component preview](https://deploy-preview-1624--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FSection&selectedStory=Course%20Index&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> Add course index

- components/section/_section-alt.css
- components/today/stories/Section/StandardWithColumns.vue
- components/today/stories/Section/ThreeUp.vue
- added a new class `.section-alt__inner-svg-icon` for the `SectionAlt` component handling icons sizes.
> fix(section): alt svg

- components/footer/PageFooterAlt.vue
Updated link based on feedback from Brendan:
Remove Alumni from footer
Add Safety and respect to the footer (in place of ‘Alumni’)
Link safety and respect to this page (https://students.unimelb.edu.au/campus-life/policy-and-conduct/respect-at-the-university)
> (fix) update to footer links

- components/index.js
- components/megamenu/MegaMenuAlt.vue
- components/megamenu/MegaMenuAltMobile.vue
- components/megamenu/__tests__/MegaMenuAlt.test.js
- components/megamenu/__tests__/MegaMenuAltMobile.test.js
- components/megamenu/__tests__/__snapshots__/MegaMenuAlt.test.js.snap
- components/megamenu/__tests__/__snapshots__/MegaMenuAltMobile.test.js.snap
- components/megamenu/_mega-menu-alt-mobile.css
- components/megamenu/_mega-menu-alt.css
- components/megamenu/index.css
- components/megamenu/stories/MegaMenuAlt.vue
- components/megamenu/stories/index.js
- components/megamenu/stories/mega-menu-alt.md
- components/screen-reader-jump-to/ScreenReaderJumpTo.vue
- components/screen-reader-jump-to/stories/Default.vue
- package.json
- targets/lib/index.js
- targets/vue/index.js
- yarn.lock
Fixes https://todaydesign.atlassian.net/browse/UOM17-123
[Mega menu Alt](https://deploy-preview-1630--pattern-lib-unimelb.netlify.app//?selectedKind=Mega%20menu&selectedStory=Mega%20Menu%20Alt%20%28Today%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): mega menu alt

- components/embed/_video.css
- components/section/_section-alt.css
- components/today/stories/Section/SectionWithVideo.vue
- components/today/stories/Section/index.js
Fixes https://todaydesign.atlassian.net/browse/UOM18B-108
> chore(component): video landscape in a section

- components/section/_section-image.css
Fixes https://app.zenhub.com/workspaces/global-design-system-issues-tracker-603c265651b123001c916450/issues/unimelb/pattern-lib/1638
> chore(css): update padding section image

- components/testimonials/_testimonials-alt.css
Fixes https://todaydesign.atlassian.net/browse/UOM18B-161
> fix(component): testimonials quote

- components/breadcrumbs/PageBreadcrumbs.vue
- components/breadcrumbs/__tests__/__snapshots__/PageBreadcrumbs.test.js.snap
Fixes https://app.zenhub.com/workspaces/global-design-system-issues-tracker-603c265651b123001c916450/issues/unimelb/pattern-lib/1651
> fix(component): breadcrumbs accessibility

- components/embed/VideoPlayer.vue
- components/embed/__tests__/__snapshots__/VideoPlayer.test.js.snap
Wrapped the  `progressive-img` component in `client-only` Nuxt component to fix DOM errors in SSR
> Update VideoPlayer component to remove DOM issues in Nuxt SSR

- components/megamenu/_mega-menu-alt.css
Fixes https://github.com/unimelb/pattern-lib/issues/1670
[Preview link](https://deploy-preview-1671--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Mega%20menu&selectedStory=Mega%20Menu%20Alt%20%28Today%29&full=1&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> chore(component): mega menu alt tweaks

- components/buttons/index.css
- components/today/PathfinderToday/index.css
Fixes https://todaydesign.atlassian.net/browse/UOM18B-218
[Preview link](https://60d2cb7e4759680008d74377--pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FPathfinder&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> fix(component): pathfinder mobile issue

- components/_utils.css
- components/cards/_card-article-large.css
- components/section/_section-alt.css
- components/testimonials/_testimonials-alt.css
Fixes: https://todaydesign.atlassian.net/browse/UOM18B-217
[Standard](https://deploy-preview-1675--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Today%2FSection&selectedStory=Standard%20%28with%20columns%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[Standard with Image](https://deploy-preview-1675--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Today%2FSection&selectedStory=Standard%20%28with%20image%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[3 up](https://deploy-preview-1675--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Today%2FSection&selectedStory=3%20Up&full=0&addons=1&stories=1&panelRigh …
> fix(css): for today sections

- components/cards/_card-course.css
- components/cards/stories/Course/Story2.vue
- components/cards/stories/Course/card-course-list.md
- components/cards/stories/Course/card-course.md
Fixes https://todaydesign.atlassian.net/browse/UOM18B-128
[Preview link](https://deploy-preview-1677--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Cards%2FCourse&selectedStory=Card%20Course%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> chore(component): add new course card type option for colour

- components/_base.css
Fixes https://todaydesign.atlassian.net/browse/UOM18B-227
> chore(input): implement base input styling

- components/megamenu/MegaMenu.vue
- components/megamenu/_mega-menu.css
- components/search/_header-tools.css
Fixes https://todaydesign.atlassian.net/browse/UOM18B-247
[Iframe preview](https://deploy-preview-1685--pattern-lib-unimelb.netlify.app/iframe.html?selectedKind=Mega%20menu&selectedStory=Mega%20Menu%20with%20Top%20nav)
> fix(component): mega menu keyboard navigation

- components/embed/VideoPlayer.vue
Added new query string to VideoPlayer component `rel=0`
Fixes https://todaydesign.atlassian.net/browse/UOM18B-251
> chore(component): video play query string

- README.md
Ticket: https://app.zenhub.com/workspaces/global-design-system-issues-tracker-603c265651b123001c916450/issues/unimelb/pattern-lib/1698
> Netlify changes

- components/footer/PageFooterAlt.vue
- components/footer/__tests__/__snapshots__/PageFooterAlt.test.js.snap
- components/footer/_page-footer-alt.css
Fixes https://github.com/unimelb/pattern-lib/issues/1690
> chore(component): page footer alt css fixes

- components/footer/PageFooterAlt.vue
- components/footer/__tests__/__snapshots__/PageFooterAlt.test.js.snap
TIcket: https://github.com/unimelb/Gen3/issues/246
> chore(footer): add label
