- pre-push.sh
This script 
- checks that the SemVer is the same as remote
- auto-increments the SemVer pre-release version number
before pushing to the dev branch
> Add pre-push git hook script

- components/section/stories/Crest/Story4.vue
- webpack.config.base.js
There are some Vue presentation components that the CMS can use but hasn't been documented in pattern library.
This PR consists of adding documentation to:
Section wrappers
> Add some documentation to section wrappers

- components/page/megamenu/_mega-menu.css
- components/page/search/_header-tools.css
Mobile menu shouldn't overlay when menu is opened
> Fix mobile menu overlaying opened menu

- components/buttons/index.css
- components/buttons/stories/ButtonAdjacent.vue
- components/buttons/stories/index.js
Buttons take up 100% of width on mobile/tablet viewports
Adjacent buttons add some spacing between themselves.
> (fix) improve buttons on mobile layout

- components/cards/_card-generic.css
https://deploy-preview-1117--pattern-lib-unimelb.netlify.com/?selectedKind=Cards%2FEvents&selectedStory=Full%20width%20%28horizontal%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
> IE11 fix for card events full width

- components/tables/CompactedTable.vue
- components/tables/_tables-compacted.css
- components/tables/_tables-responsive.css
- components/tables/stories/TableComplexCompacted.vue
- components/tables/stories/table-compacted-complex.md
Made it easier for content editor to set compacted table header.
Set responsive table to `!important` to override content editors inline `width:100%` on table
> chore(component) update compacted table header selector

- .storybook/config.js
Stop vue-axe from clearing console.  At the moment it's hard to see any errors etc.
> chore(console) Add command to stop vue-axe clearing console

- components/carousel/stories/carousel-doc.md
- targets/vue/index.js
A quick fix so we can install newer versions of `pattern-lib-vue` in find a course.
> chore(carousel) remove component from pattern-lib-vue

- .stylelintrc
Currently there is a rule to force `@` rules to be at the bottom of a class.  This causes issues with media queries in this situation:
```html
.box {
width: 50px;
height: 50px;
background: black;
&--alt {
background: orange;
@media (--bp-desktop) { 
background: green;
}
}
@media (--bp-desktop) { 
background: red;
}
}
```
```<div class="box box--alt"></div>``` should be _green_ but because of the rule ordering it is instead _red_;
By allowing `@` rule to be at the top this will now be allowed and show the correct colours:
```
.box {
width: 50px;
height: 50px;
background: black;
@media (--bp-desktop) { 
background: red;
}
&--alt { 
background: orange;
@media (--bp-desktop) { 
background: green;
}
}
}```
> chore(linting) Remove rule for @ rule to be at end of class

- components/tabs/Tabs.vue
- components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
- components/tabs/stories/TabsSelect.vue
- components/tabs/stories/tabsSelect.md
If there is only one `<tab>` inside the `<tabs>` component and `use-select` has been set, then hide the select dropdown.
> chore(component) Tabs - hide select if there is only one tab

- components/cards/CardStaffList.vue
- components/cards/__tests__/__snapshots__/CardStaffList.test.js.snap
- components/cards/_card-stafflist.css
- components/forms/_select.css
Building the new pages of short-courses for FAC, the card staff list because is been used in a white background we had the necessity to implement borders to make it stand out from the white background and looks better, this redesign will fix the problem of the usage in this card in white background.
preview: 
https://deploy-preview-1394--pattern-lib-unimelb.netlify.com/?selectedKind=Cards%2FStaff%20List%2FBios&selectedStory=Staff%20bios&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel
> feat(redesign): card staff list

- components/buttons/index.css
Fix the CSS for the button event alt, as it was getting overridden by the .btn class
> fix(component): button event alt css

- components/megamenu/MegaMenu.vue
Aria-labelledby attribute must point to IDs of elements in the same document.
This is similar to this issue:unimelb/find-a-course#1842
However the element with the ID does exist.
I suspect that this issue is caused by the incorrect use of aria-labelledby.
Fixes #1450
> using aria-label instead of aria-labelledby

- components/filters/components/filter-dropdown/FilterDropdown.vue
- components/filters/components/filter-dropdown/__tests__/__snapshots__/FilterDropdown.test.js.snap
Fix accessibility role for the dropdown in the filters
> fix(filters): dropdown role

- components/_vars.css
- components/section/SectionTwoCol.vue
- components/section/_two-column-header-text.css
- components/section/index.css
- components/section/stories/SectionTwo/Story6.vue
- components/section/stories/SectionTwo/index.js
Fixes
https://jira.unimelb.edu.au/browse/VOD-109
https://jira.unimelb.edu.au/browse/VOD-128
preview:
[header text with cta](https://deploy-preview-1469--pattern-lib-unimelb.netlify.app/?selectedKind=Section%2FTwo%20Column&selectedStory=Header%20text%20with%20cta%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> feat(component): header text with cta 2 column

- components/buttons/ButtonIcon.vue
- components/screen-reader-jump-to/ScreenReaderJumpTo.vue
- components/screen-reader-jump-to/index.css
- components/screen-reader-jump-to/stories/Default.vue
- components/screen-reader-jump-to/stories/screenReaderMd.md
These changes are related to [https://github.com/unimelb/homepage/issues/1](url)
- changes the element to button, to make the component work in Firefox
- adds the link role to change the screen reader behavior to work like with default anchor tag
- changes the position of the button to be left aligned
Also I've tested this functionality in Safari and tab navigation works only with an option button pressed (it is a default behavior for safari). When using voiceover everything works as expected.
Could you please review?
> fix(component): Screen Reader Jump To main content

- components/cards/_card-rounded-figure.css
- components/section/_split-section.css
- components/todo-list/TodoList.vue
[Preview](https://deploy-preview-1476--pattern-lib-unimelb.netlify.app/?selectedKind=Section%2FSplit%20Section&selectedStory=Left&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
> fix(component): split section order bug

- components/section/_split-section.css
Reduces padding-top so text block still looks bottom-aligned but does not have excessive whitespace above it.
> Reduce padding-top on split section text container

- components/_utils.css
- components/cards/_card-focus-box.css
- components/print.css
Reverted focus wrapper classes, as the CMS is still dependent on them.
> chore(css): add focus wrapper deprecated classes back

- components/megamenu/MegaMenu.vue
Bug fix (accessibility issues - An element with role=menuitem must be contained in, or owned by, an element with role=menu or role=menubar)
> fix accessibility role menuitem

- components/breadcrumbs/PageBreadcrumbs.vue
- components/cards/CardLink.vue
- components/cards/CardStaffList.vue
- components/filter/accordion/AccordionFilter.vue
- components/filter/cards-category/CardsFilterCategory.vue
- components/filter/cards/CardsFilter.vue
- components/filter/courses/CoursesFilter.vue
- components/filters/components/filter-dropdown/FilterDropdown.vue
- components/focus-wrapper/FocusWrapper.vue
- components/footer/PageFooterUpper.vue
- components/megamenu/MegaMenu.vue
- components/navigation/InPageNavigation.vue
- components/profiles/accordion-profile/AccordionProfile.vue
- components/quick-links-menu/QuickLinksMenuItem.vue
- components/search/PageSearch.vue
- components/search/PageSearchForm.vue
- components/side-panel/SidePanel.vue
- components/side-panel/SidePanelNavItem.vue
- components/social-media-bar/SocialMediaBar.vue
- components/sublink-menu/SublinkMenuItem.vue
I was investigating accessibility issues:
“SVG elements with graphic role attributes must have an accessible name.
SVG elements with role=img, role=graphics-document or role=graphics-symbol need an accessible name provided by the SVG title element or an ARIA label.”
Component SvgIcon takes props “name”  which we are forming “aria-label”.
I think In many components props “name” are not transferred for component SvgIcon.
Thank you
> fix accessibility svg aria label

- components/tabs/Tabs.vue
- components/tabs/__tests__/__snapshots__/Tabs.test.js.snap
I suggest that the problem is caused by the fact, that during the testing on accessibility the array panels isn't ready due to the fix: https://github.com/unimelb/pattern-lib/blob/dev/components/tabs/Tabs.vue#L185
I am adding “role: tablist” when array is ready to be rendered. This could solve the problem.
> fix accessibility tablist-must contain tab

- components/carousel/Carousel.vue
- components/carousel/__tests__/__snapshots__/Carousel.test.js.snap
- components/megamenu/MegaMenu.vue
fix: An element with role=menuitem must be contained in, or owned by, an element with role=menu or role=menubar
https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html
> fix accessibility element with role menuitem

- components/_shims.css
- components/helpers/stories/ShimMb.vue
Add additional classes for one third (.5rem) and two thirds (1rem) spacing units.
> Shim updates

- components/_shims.css
- components/helpers/stories/ShimMb.vue
- components/section/_section-alt.css
- components/today/stories/Section/Bordered.vue
- components/today/stories/Section/Columns.vue
- components/today/stories/Section/StandardWithColumns.vue
- components/today/stories/Section/ThreeUp.vue
- components/today/stories/Section/index.js
After eyeballing the sections on mobile, I think we could tighten up the spacing a bit - trying to catch this now before it's in the CMS and more difficult to update markup.
I've added some responsive helpers for the shim margin helpers.
I've also added a `Bordered` example to the docs - this is not required for the CMS, but thought it would be good to document that variation too (used on the Microcert page in FAC).
> Add bordered section to the docs, update mobile spacing

- components/megamenu/MegaMenu.vue
Fixes https://todaydesign.atlassian.net/browse/UOM18B-171
> fix(component): mega menu duplicated id with icon-menu

- components/campaign/_campaign-banner-alt.css
SiteImprove is reporting the header background as white, causing the overlaid text to fail contrast checks as it is also white. The background has been set to dark navy, but this is failing to be set as there is a typo in the CSS var name used.
This is a false positive however, as there is a dark background image plus gradient in the layers between the text and the background, so is highly legible.
- Background colour has been set, but there is a typo in the colour variable name used. This has been corrected and should enable the background colour to be set to dark navy as originally intended, which should resolve this issue.
> fix(accessibility): campaign-banner-alt background contrast

- components/_base.css
The `Normalize.css` included in the pattern-lib build resets the default focus styling for Firefox to a single black dotted line on certain button/input elements. This renders it very difficult to see on dark backgrounds.
Reported as an accessibility issue:
> Problem
> Tabs that have focus do not have borders on the right or the bottom
> SortSite is complaining about the tab borders not being visible
> Solution
> See if the outline-width and button border styles can be made visible
I've `revert`ed this Normalize change in our `base.css`, so these properties should come from the Firefox user agent stylesheet (browser defaults) instead.
> fix(accessibility): Override Normalize styles to browser defaults for Firefox focus rings

- components/section/_section-alt.css
Update the selector to fix padding on sections when two sections with just a white background are used in succession. The previous selector was applying to all sections, see https://find-a-course-preview-staging.netlify.app/find/micro-credentials/cybersecurity-technologies-for-defence/ (broken padding on mobile and reduced on desktop)
The selector is a bit ugly - initially I was trying to be a bit clever and not have to have say a default class of `section-alt--standard` but maybe that is easier. That would require a change though I presume to existing components in Matrix.
> Fix padding for sections in succession

- components/notice/index.css
- Adds a left border with contrast greater than 3:1 to the notice components in order to comply with [WCAG non-text contrast requirements](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html).
> fix(accessibility): Add left border to notices to meet non-text contrast requirements

- components/campaign/CampaignBannerAlt.vue
- components/campaign/__tests__/__snapshots__/CampaignBannerAlt.test.js.snap
- components/cards/CardFlat.vue
- components/cards/__tests__/__snapshots__/CardFlat.test.js.snap
- components/cards/__tests__/__snapshots__/CardFlatList.test.js.snap
- components/embed/VideoEmbed.vue
- components/embed/VideoPlayer.vue
- components/today/stories/Campaign/Default.vue
- components/today/stories/Campaign/Event.vue
- components/today/stories/Campaign/Large.vue
- components/today/stories/Campaign/LargeWithLinks.vue
- components/today/stories/Campaign/campaign-banner-alt.md
- components/today/stories/Cards/CardFlat.md
- components/today/stories/Cards/CardFlatList.md
- components/today/stories/Cards/CardFlatList.vue
The video component takes these parameters (label="Life at Melbourne"):
Graphical user interface, text, application, chat or text message
Description automatically generated
But outputs this iframe code (title="Youtube video)":
Text
Description automatically generated with low confidence
The title attribute of the iframe should reflect the label property
an H1 and a link are not sufficient for Campaign Banners.
eg. in the case of Open Day, we'd want something like:
Open Day
August 10, 2021
[ Join us ]
I have resolved this within our CMS https://www.unimelb.edu.au/?banner=3822735, but the pattern should probably be rolled back into the vue component with a property to generate the subheading.
A last minute request saw us add a video to a card in place of an image. (First card in last …
> Fix and improvements - homepage components
